WIP: Disposable email project.
purringCatFoundation/DisposableEmail pull request #1
Opened 2017-03-15 19:14 UTC by pradzikowski

2017-03-15 21:31 UTC, pradzikowski commented
[](http://www.catgifpage.com/gifs/318.gif)

2017-03-15 22:50 UTC, pradzikowski commented
@adeptofvoltron i was end my WIP process. I will wait for your review

2017-03-16 11:44 UTC, adeptofvoltron commented on .travis.yml
> +  - phpunit
more likely to use `./vendor/bin/phpunit` than you will make sure the travis will run proper version of phpunit

2017-03-16 11:47 UTC, adeptofvoltron commented on src/Exception/DisposableEmailException.php
> +{}
Opening class brace must be on a line by itself
Closing class brace must be on a line by itself

2017-03-16 12:31 UTC, adeptofvoltron requested changes
till `verifyDomain` is not static method, it would be nice(but not must have) to create Factry for Listed/RegexVerifier.

other hand you can create some static methods inside both methods...that allow you to verifyDomain. All dependiences are inside package.

2017-03-16 12:31 UTC, adeptofvoltron commented on src/Exception/DisposableEmailException.php
> +{}
similar on VerifyDomainException

2017-03-16 12:31 UTC, adeptofvoltron commented on src/Resource/BlockList.php
> +}
line after closing brace

2017-03-16 12:31 UTC, adeptofvoltron commented on src/Resource/BlockList.php
> +
useless empty line

2017-03-16 12:31 UTC, adeptofvoltron commented on src/RegexVerifier.php
> +        if(empty($this->collection)) {
space after if keyword

2017-03-16 12:31 UTC, adeptofvoltron commented on src/RegexVerifier.php
> +        if(empty($domain)) {
space after if keyword

2017-03-16 12:31 UTC, adeptofvoltron commented on src/RegexVerifier.php
> +        if(empty($list)) {
space after if keyword

2017-03-16 12:31 UTC, adeptofvoltron commented on src/RegexVerifier.php
> +            if(true === $this->pregList($list, $domain)) {
space after if keyword

2017-03-16 12:31 UTC, adeptofvoltron commented on src/RegexVerifier.php
> +            if(true == preg_match($pattern, $domain)) { //IHATETHISFUNCTIONBECAUSEITRETURNINTINTEADBOOLEAN
space after if keyword

2017-03-16 12:31 UTC, adeptofvoltron commented on src/EmailVerifierInterface.php
> +Interface EmailVerifierInterface
`I` => `i`

2017-03-16 12:31 UTC, adeptofvoltron commented on src/ListedVerifier.php
> +namespace PCF\DisposableEmail;
line after namespace

2017-03-16 12:31 UTC, adeptofvoltron commented on src/ListedVerifier.php
> +        if(empty($this->collection)) {
space after if keyword

2017-03-16 12:31 UTC, adeptofvoltron commented on src/ListedVerifier.php
> +        if(empty($domain)) {
space after if keyword

2017-03-16 12:31 UTC, adeptofvoltron commented on src/ListedVerifier.php
> +            if(empty($list)) {
space after if keyword

2017-03-16 12:31 UTC, adeptofvoltron commented on src/ListedVerifier.php
> +            if(in_array($domain, $list)){
space after if keyword and one before brace

2017-03-16 12:31 UTC, adeptofvoltron commented on test/RegexVerifierTest.php
> +
expected one blank line...not two

2017-03-16 12:31 UTC, adeptofvoltron commented on test/RegexVerifierTest.php
> +}
expected one blank line at the end of file

2017-03-16 12:31 UTC, adeptofvoltron commented on src/RegexVerifier.php
> +            if(true == preg_match($pattern, $domain)) { //IHATETHISFUNCTIONBECAUSEITRETURNINTINTEADBOOLEAN
`HP Warning:  preg_match(): Delimiter must not be alphanumeric or backslash in /home/praca/Pulpit/DisposableEmail/src/RegexVerifier.php on line 83`

2017-03-16 12:31 UTC, adeptofvoltron commented on src/RegexVerifier.php
> +            if(true == preg_match($pattern, $domain)) { //IHATETHISFUNCTIONBECAUSEITRETURNINTINTEADBOOLEAN
useless comment

2017-03-16 12:40 UTC, adeptofvoltron commented on src/Resource/AbstractResourceList.php
> +        return explode(PHP_EOL, trim(static::$list));
topic to discuss: You can copy list from [source](https://github.com/martenson/disposable-email-domains) as a text. But in other hands, thi lib will be more efficient if we would allready keep list as array

2017-03-16 19:39 UTC, pradzikowski commented on src/RegexVerifier.php
> +            if(true == preg_match($pattern, $domain)) { //IHATETHISFUNCTIONBECAUSEITRETURNINTINTEADBOOLEAN
stfu :D

2017-03-18 08:48 UTC, pradzikowski commented on .travis.yml
> +  - phpunit
Sure, I will fix this.

2017-03-18 08:48 UTC, pradzikowski commented on src/Exception/DisposableEmailException.php
> +{}
👌

2017-03-18 08:55 UTC, pradzikowski commented on src/RegexVerifier.php
> +            if(true == preg_match($pattern, $domain)) { //IHATETHISFUNCTIONBECAUSEITRETURNINTINTEADBOOLEAN
Could you show me you runtime code ? what pattern you use ?

2017-03-18 09:12 UTC, pradzikowski commented on src/Resource/AbstractResourceList.php
> +        return explode(PHP_EOL, trim(static::$list));
I think about it and yes i will clone source files as original. Imo this is not reasonable to be afraid about perfomance and efficient in this case. Users and frameworks can cache this data in faster storages than static txt. 

Current frameworks have fine mechanism for caching static resources (ex. routing)for example [syfony](http://symfony.com/doc/current/components/dependency_injection/compilation.html)

2017-03-18 09:17 UTC, pradzikowski commented
@adeptofvoltron Imo i dont need to create factories for these classes because their implementation deeply based on users code. Of course i can create factory only for our resources but i dont think we need this. Maybe i will create builder, but i dont promise.

2017-03-19 09:18 UTC, pradzikowski commented
https://www.catgifpage.com/cute

@adeptofvoltron done :)

2017-03-19 09:27 UTC, pradzikowski commented on test/RegexVerifierTest.php
> +
done

2017-03-19 09:27 UTC, pradzikowski commented on test/RegexVerifierTest.php
> +}
done

2017-03-19 09:27 UTC, pradzikowski commented on src/ListedVerifier.php
> +namespace PCF\DisposableEmail;
done

2017-03-19 09:27 UTC, pradzikowski commented on src/RegexVerifier.php
> +            if(true === $this->pregList($list, $domain)) {
done

2017-03-19 11:55 UTC, closed without merging