Init disposable email project
purringCatFoundation/DisposableEmail pull request #2
Opened 2017-03-19 12:10 UTC by pradzikowski

I was closed last mail because i made some mess with flating my commits.
So i was rebuild my copy and create new MR.

So i'm waiting for MR:

![](https://media.giphy.com/media/pTEpAI1TfqV2w/giphy.gif)

2017-03-19 16:28 UTC, adeptofvoltron requested changes
change the example in README.md to working one

2017-03-19 16:28 UTC, adeptofvoltron commented on test/AbstractPCFVerifierTest.php
> +            protected function doVerifyDomain(string $domain): int {
Opening brace should be on a new line

2017-03-19 16:28 UTC, adeptofvoltron commented on test/AbstractPCFVerifierTest.php
> +            protected function doVerifyDomain(string $domain): int {
Opening brace should be on a new line

2017-03-19 16:28 UTC, adeptofvoltron commented on test/AbstractPCFVerifierTest.php
> +            protected function doVerifyDomain(string $domain): int {
Opening brace should be on a new line

2017-03-19 16:28 UTC, adeptofvoltron commented on README.md
> +use PCF\DisposableEmail\Resource\BlockList;
it not exist anymore

2017-03-19 16:28 UTC, adeptofvoltron commented on README.md
> +use PCF\DisposableEmail\Resource\TrustList;
it not exist anymore

2017-03-19 20:19 UTC, pradzikowski commented on test/AbstractPCFVerifierTest.php
> +            protected function doVerifyDomain(string $domain): int {
done

2017-03-19 20:19 UTC, pradzikowski commented on test/AbstractPCFVerifierTest.php
> +            protected function doVerifyDomain(string $domain): int {
done

2017-03-19 20:19 UTC, pradzikowski commented on test/AbstractPCFVerifierTest.php
> +            protected function doVerifyDomain(string $domain): int {
done

2017-03-19 21:33 UTC, pradzikowski commented
@adeptofvoltron done

2017-03-20 18:23 UTC, adeptofvoltron approved these changes

2017-03-20 18:29 UTC, adeptofvoltron requested changes
Conflicted

2017-03-20 18:29 UTC, adeptofvoltron commented on test/AbstractPCFVerifierTest.php
> +            protected function doVerifyDomain(string $domain): int {
brace

2017-03-21 21:41 UTC, merged